Calvin:
  allowance: 15
  email: calvinmichaelfelker@gmail.com
Carly:
  allowance: 100
  email: carlyfelker@gmail.com
Jamo:
  allowance: 0
  email: ''
Lilah:
  allowance: 15
  email: lilahfelker@gmail.com
Travis:
  allowance: 100
  email: travisjfelker@gmail.com
